import 'dotenv/config';
import express from 'express';
import bodyParser from 'body-parser';
import cors from 'cors';
import { generateScript } from './llamaClient.js';
import { validateScript } from './validator.js';
import { initDB, logPrompt } from './store.js';

const app = express();
app.use(bodyParser.json({ limit: '2mb' }));

const allowOrigins = (process.env.ALLOW_ORIGINS || '*').split(',');
app.use(cors({ origin: (origin, cb) => {
  if (!origin || allowOrigins.includes('*') || allowOrigins.includes(origin)) return cb(null, origin || '*');
  return cb(new Error('Origin not allowed'));
}}));

await initDB();

app.get('/health', (_req, res) => res.json({ ok: true }));

app.post('/generate', async (req, res) => {
  const { prompt, context } = req.body || {};
  if (!prompt || typeof prompt !== 'string') return res.status(400).json({ error: 'prompt required' });
  try {
    const script = await generateScript(prompt, context);
    validateScript(script);
    await logPrompt(prompt, context || '', script);
    res.json({ script, description: 'Generated by Prim8' });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

const port = Number(process.env.PORT || 5000);
app.listen(port, () => console.log(`Prim8 backend listening on :${port}`));
